"""
Wizard of Oz Rehearsal Planner — Section Data

All rehearsable sections of the show, with vocal metadata for crosscasting.
Edit this file to add/remove/update sections.
"""

SECTIONS = [
    # --- NO. 1 – OPENING ---
    {
        "id": "no1_opening_girls_chorus",
        "song": "No. 1 – Opening",
        "section": "Girls chorus",
        "characters": ["Girls Chorus"],
        "vocal_type": "ensemble",
        "harmony_role": "mixed",
        "audition_priority": 1,
        "harmony_difficulty": 2,
    },

    # --- NO. 4 – OVER THE RAINBOW ---
    {
        "id": "no4_otr_dorothy_full",
        "song": "No. 4 – Over the Rainbow",
        "section": "Dorothy solo (full song)",
        "characters": ["Dorothy"],
        "vocal_type": "solo",
        "harmony_role": "unison",
        "audition_priority": 3,
        "harmony_difficulty": 1,
    },

    # --- NO. 9 – MUNCHKINLAND ---
    {
        "id": "no9_munch_girls_3part",
        "song": "No. 9 – Munchkinland",
        "section": "Girls chorus (3-part high)",
        "characters": ["Girls Chorus"],
        "vocal_type": "ensemble",
        "harmony_role": "high",
        "audition_priority": 2,
        "harmony_difficulty": 3,
    },

    # --- NO. 10–11 – MUNCHKIN SEQUENCE / DING DONG ---
    {
        "id": "no10_munch_glinda",
        "song": "No. 10–11 – Munchkin Musical Sequence / Ding Dong",
        "section": "Glinda lead lines",
        "characters": ["Glinda"],
        "vocal_type": "solo",
        "harmony_role": "high",
        "audition_priority": 3,
        "harmony_difficulty": 1,
    },
    {
        "id": "no10_munch_munchkins_unison",
        "song": "No. 10–11 – Munchkin Musical Sequence / Ding Dong",
        "section": "Munchkin unison phrases",
        "characters": ["Munchkins"],
        "vocal_type": "ensemble",
        "harmony_role": "unison",
        "audition_priority": 1,
        "harmony_difficulty": 1,
    },
    {
        "id": "no10_munch_dorothy_lines",
        "song": "No. 10–11 – Munchkin Musical Sequence / Ding Dong",
        "section": "Dorothy vocal responses",
        "characters": ["Dorothy"],
        "vocal_type": "solo",
        "harmony_role": "unison",
        "audition_priority": 2,
        "harmony_difficulty": 1,
    },
    {
        "id": "no10_munch_braggart_solo",
        "song": "No. 10–11 – Munchkin Musical Sequence / Ding Dong",
        "section": "Munchkin Braggart solo",
        "characters": ["Braggart"],
        "vocal_type": "solo",
        "harmony_role": "middle",
        "audition_priority": 2,
        "harmony_difficulty": 1,
    },
    {
        "id": "no10_munch_several_unison",
        "song": "No. 10–11 – Munchkin Musical Sequence / Ding Dong",
        "section": "Several Munchkins unison",
        "characters": ["Munchkins"],
        "vocal_type": "ensemble",
        "harmony_role": "unison",
        "audition_priority": 1,
        "harmony_difficulty": 1,
    },
    {
        "id": "no10_munch_teacher12_spoken",
        "song": "No. 10–11 – Munchkin Musical Sequence / Ding Dong",
        "section": "Teachers 1 & 2 spoken bits",
        "characters": ["Teacher 1", "Teacher 2"],
        "vocal_type": "spoken",
        "harmony_role": "unison",
        "audition_priority": 1,
        "harmony_difficulty": 1,
    },
    {
        "id": "no10_munch_mayor_spoken",
        "song": "No. 10–11 – Munchkin Musical Sequence / Ding Dong",
        "section": "Mayor spoken bits",
        "characters": ["Mayor"],
        "vocal_type": "spoken",
        "harmony_role": "unison",
        "audition_priority": 2,
        "harmony_difficulty": 1,
    },
    {
        "id": "no10_munch_barrister_spoken",
        "song": "No. 10–11 – Munchkin Musical Sequence / Ding Dong",
        "section": "Barrister spoken bits",
        "characters": ["Barrister"],
        "vocal_type": "spoken",
        "harmony_role": "unison",
        "audition_priority": 1,
        "harmony_difficulty": 1,
    },
    {
        "id": "no10_munch_city_fathers_spoken",
        "song": "No. 10–11 – Munchkin Musical Sequence / Ding Dong",
        "section": "City Fathers 1–3 spoken bits",
        "characters": ["City Father 1", "City Father 2", "City Father 3"],
        "vocal_type": "spoken",
        "harmony_role": "unison",
        "audition_priority": 1,
        "harmony_difficulty": 1,
    },
    {
        "id": "no10_munch_coroner_solo",
        "song": "No. 10–11 – Munchkin Musical Sequence / Ding Dong",
        "section": "Coroner solo",
        "characters": ["Coroner"],
        "vocal_type": "solo",
        "harmony_role": "middle",
        "audition_priority": 3,
        "harmony_difficulty": 1,
    },
    {
        "id": "no10_munch_three_tots",
        "song": "No. 10–11 – Munchkin Musical Sequence / Ding Dong",
        "section": "Three Tots harmony",
        "characters": ["Three Tots"],
        "vocal_type": "small_group",
        "harmony_role": "high",
        "audition_priority": 2,
        "harmony_difficulty": 3,
    },
    {
        "id": "no10_munch_three_tough_kids",
        "song": "No. 10–11 – Munchkin Musical Sequence / Ding Dong",
        "section": "Three Tough Kids harmony",
        "characters": ["Three Tough Kids"],
        "vocal_type": "small_group",
        "harmony_role": "middle",
        "audition_priority": 2,
        "harmony_difficulty": 3,
    },
    {
        "id": "no10_munch_group_harmony",
        "song": "No. 10–11 – Munchkin Musical Sequence / Ding Dong",
        "section": "Group harmony (all munchkins)",
        "characters": ["Munchkins"],
        "vocal_type": "ensemble",
        "harmony_role": "mixed",
        "audition_priority": 2,
        "harmony_difficulty": 2,
    },

    # --- NO. 14 – YELLOW BRICK ROAD ---
    {
        "id": "no14_ybr_mayor_solo",
        "song": "No. 14 – Yellow Brick Road",
        "section": "Mayor solo",
        "characters": ["Mayor"],
        "vocal_type": "solo",
        "harmony_role": "middle",
        "audition_priority": 2,
        "harmony_difficulty": 1,
    },
    {
        "id": "no14_ybr_coroner_lines",
        "song": "No. 14 – Yellow Brick Road",
        "section": "Coroner lines",
        "characters": ["Coroner"],
        "vocal_type": "solo",
        "harmony_role": "middle",
        "audition_priority": 2,
        "harmony_difficulty": 1,
    },
    {
        "id": "no14_ybr_munchkins",
        "song": "No. 14 – Yellow Brick Road",
        "section": "Munchkins chorus",
        "characters": ["Munchkins"],
        "vocal_type": "ensemble",
        "harmony_role": "mixed",
        "audition_priority": 1,
        "harmony_difficulty": 2,
    },
    {
        "id": "no14_ybr_fiddler_solo",
        "song": "No. 14 – Yellow Brick Road",
        "section": "Fiddler solo",
        "characters": ["Fiddler"],
        "vocal_type": "solo",
        "harmony_role": "high",
        "audition_priority": 2,
        "harmony_difficulty": 1,
    },

    # --- NO. 16 – IF I ONLY HAD A BRAIN ---
    {
        "id": "no16_brain_scarecrow_solo",
        "song": "No. 16 – If I Only Had a Brain",
        "section": "Scarecrow solo & verse",
        "characters": ["Scarecrow"],
        "vocal_type": "solo",
        "harmony_role": "middle",
        "audition_priority": 3,
        "harmony_difficulty": 1,
    },
    {
        "id": "no16_brain_crows_trio",
        "song": "No. 16 – If I Only Had a Brain",
        "section": "Three Crows harmony",
        "characters": ["Crows"],
        "vocal_type": "small_group",
        "harmony_role": "mixed",
        "audition_priority": 3,
        "harmony_difficulty": 3,
    },
    {
        "id": "no16_brain_dorothy_spoken",
        "song": "No. 16 – If I Only Had a Brain",
        "section": "Dorothy spoken lines",
        "characters": ["Dorothy"],
        "vocal_type": "spoken",
        "harmony_role": "unison",
        "audition_priority": 1,
        "harmony_difficulty": 1,
    },

    # --- NO. 17 – WE'RE OFF TO SEE THE WIZARD (duet) ---
    {
        "id": "no17_wiz_duet_ds",
        "song": "No. 17 – We're Off to See the Wizard",
        "section": "Duet (Dorothy & Scarecrow)",
        "characters": ["Dorothy", "Scarecrow"],
        "vocal_type": "small_group",
        "harmony_role": "unison",
        "audition_priority": 2,
        "harmony_difficulty": 1,
    },

    # --- NO. 19 – IF I ONLY HAD A HEART ---
    {
        "id": "no19_heart_tinman_solo",
        "song": "No. 19 – If I Only Had a Heart",
        "section": "Tinman solo & main line",
        "characters": ["Tinman"],
        "vocal_type": "solo",
        "harmony_role": "middle",
        "audition_priority": 3,
        "harmony_difficulty": 1,
    },
    {
        "id": "no19_heart_trees_trio",
        "song": "No. 19 – If I Only Had a Heart",
        "section": "Three Trees interjections",
        "characters": ["Trees"],
        "vocal_type": "small_group",
        "harmony_role": "mixed",
        "audition_priority": 3,
        "harmony_difficulty": 3,
    },
    {
        "id": "no19_heart_dorothy_lines",
        "song": "No. 19 – If I Only Had a Heart",
        "section": "Dorothy solo / octave harmony bits",
        "characters": ["Dorothy"],
        "vocal_type": "small_group",
        "harmony_role": "unison",
        "audition_priority": 2,
        "harmony_difficulty": 1,
    },

    # --- NO. 21 – WE'RE OFF TO SEE THE WIZARD (trio) ---
    {
        "id": "no21_wiz_trio_dst",
        "song": "No. 21 – We're Off to See the Wizard",
        "section": "Trio (Dorothy, Scarecrow, Tinman)",
        "characters": ["Dorothy", "Scarecrow", "Tinman"],
        "vocal_type": "small_group",
        "harmony_role": "unison",
        "audition_priority": 2,
        "harmony_difficulty": 1,
    },

    # --- NO. 23 – IF I ONLY HAD THE NERVE ---
    {
        "id": "no23_nerve_lion_solo",
        "song": "No. 23 – If I Only Had the Nerve",
        "section": "Lion solo",
        "characters": ["Lion"],
        "vocal_type": "solo",
        "harmony_role": "middle",
        "audition_priority": 3,
        "harmony_difficulty": 1,
    },
    {
        "id": "no23_nerve_trio_support",
        "song": "No. 23 – If I Only Had the Nerve",
        "section": "Dorothy, Scarecrow, Tinman unison support",
        "characters": ["Dorothy", "Scarecrow", "Tinman"],
        "vocal_type": "small_group",
        "harmony_role": "unison",
        "audition_priority": 2,
        "harmony_difficulty": 1,
    },

    # --- NO. 23a – WIZARD REPRISE (quartet) ---
    {
        "id": "no23a_wiz_quartet_dstl",
        "song": "No. 23a – We're Off to See the Wizard (Reprise)",
        "section": "Quartet (Dorothy, Scarecrow, Tinman, Lion)",
        "characters": ["Dorothy", "Scarecrow", "Tinman", "Lion"],
        "vocal_type": "small_group",
        "harmony_role": "unison",
        "audition_priority": 2,
        "harmony_difficulty": 1,
    },

    # --- NO. 24 – POPPIES ---
    {
        "id": "no24_poppies_girls",
        "song": "No. 24 – Poppies",
        "section": "Girls chorus (4-part harmony)",
        "characters": ["Girls Chorus"],
        "vocal_type": "ensemble",
        "harmony_role": "mixed",
        "audition_priority": 2,
        "harmony_difficulty": 3,
    },
    {
        "id": "no24_poppies_boys",
        "song": "No. 24 – Poppies",
        "section": "Boys chorus (unison / 3-part)",
        "characters": ["Boys Chorus"],
        "vocal_type": "ensemble",
        "harmony_role": "mixed",
        "audition_priority": 2,
        "harmony_difficulty": 2,
    },
    {
        "id": "no24_poppies_glinda",
        "song": "No. 24 – Poppies",
        "section": "Glinda solo",
        "characters": ["Glinda"],
        "vocal_type": "solo",
        "harmony_role": "high",
        "audition_priority": 3,
        "harmony_difficulty": 1,
    },
    {
        "id": "no24_poppies_round_quartet",
        "song": "No. 24 – Poppies",
        "section": "Round (Dorothy, Scarecrow, Tinman, Lion)",
        "characters": ["Dorothy", "Scarecrow", "Tinman", "Lion"],
        "vocal_type": "small_group",
        "harmony_role": "mixed",
        "audition_priority": 3,
        "harmony_difficulty": 3,
    },

    # --- NO. 26-II – ENTR'ACTE PART TWO ---
    {
        "id": "no26_entracte_girls_offstage",
        "song": "No. 26-II – Entr'acte (Part 2)",
        "section": "Girls chorus offstage (3-part harmony)",
        "characters": ["Girls Chorus"],
        "vocal_type": "ensemble",
        "harmony_role": "mixed",
        "audition_priority": 1,
        "harmony_difficulty": 3,
    },

    # --- NO. 28 – THE MERRY OLD LAND OF OZ ---
    {
        "id": "no28_merry_dorothy",
        "song": "No. 28 – The Merry Old Land of Oz",
        "section": "Dorothy lines",
        "characters": ["Dorothy"],
        "vocal_type": "solo",
        "harmony_role": "unison",
        "audition_priority": 2,
        "harmony_difficulty": 1,
    },
    {
        "id": "no28_merry_scarecrow",
        "song": "No. 28 – The Merry Old Land of Oz",
        "section": "Scarecrow lines",
        "characters": ["Scarecrow"],
        "vocal_type": "solo",
        "harmony_role": "unison",
        "audition_priority": 2,
        "harmony_difficulty": 1,
    },
    {
        "id": "no28_merry_tinman",
        "song": "No. 28 – The Merry Old Land of Oz",
        "section": "Tinman lines",
        "characters": ["Tinman"],
        "vocal_type": "solo",
        "harmony_role": "unison",
        "audition_priority": 2,
        "harmony_difficulty": 1,
    },
    {
        "id": "no28_merry_lion",
        "song": "No. 28 – The Merry Old Land of Oz",
        "section": "Lion lines",
        "characters": ["Lion"],
        "vocal_type": "solo",
        "harmony_role": "unison",
        "audition_priority": 2,
        "harmony_difficulty": 1,
    },
    {
        "id": "no28_merry_guard",
        "song": "No. 28 – The Merry Old Land of Oz",
        "section": "Emerald City Guard lines",
        "characters": ["Emerald City Guard"],
        "vocal_type": "solo",
        "harmony_role": "middle",
        "audition_priority": 3,
        "harmony_difficulty": 1,
    },
    {
        "id": "no28_merry_girls_spoken",
        "song": "No. 28 – The Merry Old Land of Oz",
        "section": "Girls spoken bits",
        "characters": ["Girls"],
        "vocal_type": "spoken",
        "harmony_role": "unison",
        "audition_priority": 1,
        "harmony_difficulty": 1,
    },
    {
        "id": "no28_merry_beauticians",
        "song": "No. 28 – The Merry Old Land of Oz",
        "section": "Girls – Beauticians",
        "characters": ["Beauticians"],
        "vocal_type": "small_group",
        "harmony_role": "high",
        "audition_priority": 3,
        "harmony_difficulty": 3,
    },
    {
        "id": "no28_merry_polishers",
        "song": "No. 28 – The Merry Old Land of Oz",
        "section": "Boys – Polishers",
        "characters": ["Polishers"],
        "vocal_type": "small_group",
        "harmony_role": "middle",
        "audition_priority": 3,
        "harmony_difficulty": 3,
    },
    {
        "id": "no28_merry_manicurists",
        "song": "No. 28 – The Merry Old Land of Oz",
        "section": "Girls – Manicurists",
        "characters": ["Manicurists"],
        "vocal_type": "small_group",
        "harmony_role": "high",
        "audition_priority": 2,
        "harmony_difficulty": 3,
    },
    {
        "id": "no28_merry_ensemble",
        "song": "No. 28 – The Merry Old Land of Oz",
        "section": "Ozians / general ensemble",
        "characters": ["Ozians"],
        "vocal_type": "ensemble",
        "harmony_role": "mixed",
        "audition_priority": 1,
        "harmony_difficulty": 2,
    },

    # --- NO. 29 – REPRISE: MERRY OLD LAND OF OZ ---
    {
        "id": "no29_merry_reprise_ensemble",
        "song": "No. 29 – Reprise: The Merry Old Land of Oz",
        "section": "Ensemble unison",
        "characters": ["Ozians"],
        "vocal_type": "ensemble",
        "harmony_role": "unison",
        "audition_priority": 1,
        "harmony_difficulty": 1,
    },

    # --- NO. 30 – IF I WERE KING OF THE FOREST ---
    {
        "id": "no30_king_lion_main",
        "song": "No. 30 – If I Were King of the Forest",
        "section": "Lion main solo",
        "characters": ["Lion"],
        "vocal_type": "solo",
        "harmony_role": "middle",
        "audition_priority": 3,
        "harmony_difficulty": 1,
    },
    {
        "id": "no30_king_trio_support",
        "song": "No. 30 – If I Were King of the Forest",
        "section": "Dorothy, Scarecrow, Tinman harmony support",
        "characters": ["Dorothy", "Scarecrow", "Tinman"],
        "vocal_type": "small_group",
        "harmony_role": "mixed",
        "audition_priority": 2,
        "harmony_difficulty": 2,
    },

    # --- NO. 34/34a – MARCH OF THE WINKIES ---
    {
        "id": "no34_winkies_march_octaves",
        "song": "No. 34/34a – March of the Winkies",
        "section": "Winkies march / chant (octaves)",
        "characters": ["Winkies"],
        "vocal_type": "ensemble",
        "harmony_role": "low",
        "audition_priority": 2,
        "harmony_difficulty": 2,
    },
    {
        "id": "no34_winkies_captain",
        "song": "No. 34/34a – March of the Winkies",
        "section": "Winkie Captain featured lines",
        "characters": ["Winkie Captain"],
        "vocal_type": "solo",
        "harmony_role": "middle",
        "audition_priority": 3,
        "harmony_difficulty": 1,
    },

    # --- NO. 36 – JITTERBUG ---
    {
        "id": "no36_jitter_dorothy",
        "song": "No. 36 – Jitterbug",
        "section": "Dorothy (spoken then sung)",
        "characters": ["Dorothy"],
        "vocal_type": "solo",
        "harmony_role": "unison",
        "audition_priority": 2,
        "harmony_difficulty": 1,
    },
    {
        "id": "no36_jitter_scarecrow",
        "song": "No. 36 – Jitterbug",
        "section": "Scarecrow lines",
        "characters": ["Scarecrow"],
        "vocal_type": "solo",
        "harmony_role": "unison",
        "audition_priority": 2,
        "harmony_difficulty": 1,
    },
    {
        "id": "no36_jitter_tinman",
        "song": "No. 36 – Jitterbug",
        "section": "Tinman lines",
        "characters": ["Tinman"],
        "vocal_type": "solo",
        "harmony_role": "unison",
        "audition_priority": 2,
        "harmony_difficulty": 1,
    },
    {
        "id": "no36_jitter_lion",
        "song": "No. 36 – Jitterbug",
        "section": "Lion lines",
        "characters": ["Lion"],
        "vocal_type": "solo",
        "harmony_role": "unison",
        "audition_priority": 2,
        "harmony_difficulty": 1,
    },
    {
        "id": "no36_jitter_chorus",
        "song": "No. 36 – Jitterbug",
        "section": "Jitterbug 3-part chorus",
        "characters": ["Jitterbug Chorus"],
        "vocal_type": "ensemble",
        "harmony_role": "mixed",
        "audition_priority": 3,
        "harmony_difficulty": 3,
    },
    {
        "id": "no36_jitter_featured",
        "song": "No. 36 – Jitterbug",
        "section": "Featured Jitterbugs",
        "characters": ["Featured Jitterbugs"],
        "vocal_type": "small_group",
        "harmony_role": "high",
        "audition_priority": 3,
        "harmony_difficulty": 3,
    },

    # --- NO. 37 – REPRISE: JITTERBUG ---
    {
        "id": "no37_jitter_reprise",
        "song": "No. 37 – Reprise: Jitterbug",
        "section": "Jitterbug chorus reprise",
        "characters": ["Jitterbug Chorus"],
        "vocal_type": "ensemble",
        "harmony_role": "mixed",
        "audition_priority": 2,
        "harmony_difficulty": 2,
    },

    # --- NO. 40a – REPRISE: WINKIES MARCH ---
    {
        "id": "no40_winkies_reprise_march",
        "song": "No. 40a – Reprise: Winkies March",
        "section": "Winkies march reprise",
        "characters": ["Winkies"],
        "vocal_type": "ensemble",
        "harmony_role": "low",
        "audition_priority": 2,
        "harmony_difficulty": 2,
    },

    # --- NO. 41 – WINKIES MARCH WITH FRIENDS / OTR REPRISE ---
    {
        "id": "no41_winkies_with_friends",
        "song": "No. 41 – Winkies March with Friends & Reprise: Over the Rainbow",
        "section": "Winkies with friends",
        "characters": ["Winkies"],
        "vocal_type": "ensemble",
        "harmony_role": "low",
        "audition_priority": 2,
        "harmony_difficulty": 2,
    },
    {
        "id": "no41_otr_reprise_dorothy",
        "song": "No. 41 – Winkies March with Friends & Reprise: Over the Rainbow",
        "section": "Over the Rainbow reprise (Dorothy)",
        "characters": ["Dorothy"],
        "vocal_type": "solo",
        "harmony_role": "unison",
        "audition_priority": 3,
        "harmony_difficulty": 1,
    },

    # --- NO. 43 – REPRISE: DING DONG! THE WITCH IS DEAD ---
    {
        "id": "no43_dingdong_reprise_winkies",
        "song": "No. 43 – Reprise: Ding Dong! The Witch Is Dead",
        "section": "Winkies unison",
        "characters": ["Winkies"],
        "vocal_type": "ensemble",
        "harmony_role": "low",
        "audition_priority": 1,
        "harmony_difficulty": 2,
    },
]


def all_characters():
    """Return sorted list of all unique character names across all sections."""
    names = set()
    for sec in SECTIONS:
        for c in sec["characters"]:
            names.add(c)
    return sorted(names)


ALL_CHARACTERS = all_characters()

# Character groups for easier selection in the UI
CHARACTER_GROUPS = [
    ("Leads", [
        "Dorothy", "Scarecrow", "Tinman", "Lion", "Glinda",
    ]),
    ("Solo / Featured Roles", [
        "Barrister", "Braggart", "City Father 1", "City Father 2", "City Father 3",
        "Coroner", "Emerald City Guard", "Fiddler", "Mayor",
        "Teacher 1", "Teacher 2", "Three Tots", "Three Tough Kids", "Winkie Captain",
    ]),
    ("Ensemble", [
        "Beauticians", "Boys Chorus", "Crows", "Featured Jitterbugs",
        "Girls", "Girls Chorus", "Jitterbug Chorus",
        "Manicurists", "Munchkins", "Ozians", "Polishers", "Trees", "Winkies",
    ]),
]
